name: Konstellation Secrets Scanning

on:
  push:
    tags:
    branches:
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    name: Trufflehog | Scan for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Secrets scanning
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          # base: ${{ github.event.repository.default_branch }}
          # head: HEAD
          extra_args: --debug --only-verified --trace

  gitleaks:
    name: Gitleaks | Scan for secrets
    runs-on: ubuntu-latest
    steps:
    # Fetch all history from all branches and tags
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: gitleaks-action
      # uses: zricethezav/gitleaks-action@v1.6.0
      uses: zricethezav/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      # with:
      #   https://github.com/zricethezav/gitleaks#configuration
      #   https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
      #   config-path: security/.gitleaks.toml