name: Docker build workflow 

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      component_helm_tag:
        required: false
        type: string
      component_path:
        required: true
        type: string
      component_app:
        required: false
        type: boolean
        default: false
      component_image:
        required: true
        type: string
      values_file:
        required: false
        type: string
      chart_file:
        required: false
        type: string
      not_change_file:
        required: false
        type: boolean
        default: false
    secrets:
      pat:
        required: true
      docker_username:
        required: true
      docker_token:
        required: true

jobs:
  create-release-tag:
    if: github.ref == 'refs/heads/main' # only in main branch
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.release_tag_component.outputs.tag }}${{ steps.release_tag_app.outputs.tag }}${{ steps.release_tag_not_component.outputs.tag }}
      version: ${{ steps.release_tag_component.outputs.version }}${{ steps.release_tag_app.outputs.version }}${{ steps.release_tag_not_component.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.pat }}

      - if: ${{ !inputs.component_app && !inputs.not_change_file }} 
        name: Generate a release tag for component
        uses: intelygenz/monorepo-tagger-action@v2.0.3
        id: release_tag_component
        with:
          mode: 'component'
          type: 'final'
          component-prefix: "${{ inputs.component }}-"
          update-versions-in: '[{"file": "${{ inputs.values_file }}", "property": "${{ inputs.component_helm_tag }}"}]'
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}

      - if: ${{ inputs.not_change_file }}
        name: Generate a release tag for component and not change file
        uses: intelygenz/monorepo-tagger-action@v2.0.3
        id: release_tag_not_component
        with:
          mode: 'component'
          type: 'final'
          component-prefix: "${{ inputs.component }}-"
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}

      - if: ${{ inputs.component_app }}
        name: Generate a release tag for component app
        uses: intelygenz/monorepo-tagger-action@v2.0.3
        id: release_tag_app
        with:
          mode: 'component'
          type: 'final'
          component-prefix: "${{ inputs.component }}-"
          update-versions-in: '[{"file": "${{ inputs.values_file }}", "property": "${{ inputs.component_helm_tag }}"}, {"file": "${{ inputs.chart_file }}", "property": "appVersion"}]'
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}

  create-fix-tag:
    if: |
      startsWith(github.ref, 'refs/heads/release') && 
      github.event_name != 'pull_request'
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.fix_tag_component.outputs.tag }}${{ steps.fix_tag_app.outputs.tag }}${{ steps.fix_tag_not_component.outputs.tag }}
      version: ${{ steps.fix_tag_component.outputs.version }}${{ steps.fix_tag_app.outputs.version }}${{ steps.fix_tag_not_component.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.pat }}

      - uses: chrisdickinson/setup-yq@latest
      - name: Get component versions
        id: component_version
        run: |
          TAG=`yq r ${{ inputs.values_file }} '${{ inputs.component_helm_tag }}'`
          echo "TAG=${TAG##*:}" >> $GITHUB_OUTPUT
          echo Component version in release branch is ${TAG##*:}

      - if: ${{ !inputs.component_app && !inputs.not_change_file }}
        name: Generate a fix tag for component
        uses: intelygenz/monorepo-tagger-action@v2.0.3
        id: fix_tag_component
        with:
          mode: 'component'
          type: 'fix'
          component-prefix: "${{ inputs.component }}-"
          current-tag: ${{ steps.component_version.outputs.TAG }}
          update-versions-in: '[{"file": "${{ inputs.values_file }}", "property": "${{ inputs.component_helm_tag }}"}]'
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}

      - if: ${{ inputs.not_change_file }}
        name: Generate a fix tag for component and not change file
        uses: intelygenz/monorepo-tagger-action@v2.0.3
        id: fix_tag_not_component
        with:
          mode: 'component'
          type: 'fix'
          component-prefix: "${{ inputs.component }}-"
          current-tag: ${{ steps.component_version.outputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}

      - if: ${{ inputs.component_app }}
        name: Generate a fix tag for component app
        uses: intelygenz/monorepo-tagger-action@v2.0.3
        id: fix_tag_app
        with:
          mode: 'component'
          type: 'fix'
          component-prefix: "${{ inputs.component }}-"
          current-tag: ${{ steps.component_version.outputs.TAG }}
          update-versions-in: '[{"file": "${{ inputs.values_file }}", "property": "${{ inputs.component_helm_tag }}"}, {"file": "${{ inputs.chart_file }}", "property": "appVersion"}]'
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}

  build-release:
    if: | 
      always() && 
      (needs.create-release-tag.outputs.tag || needs.create-fix-tag.outputs.tag)
    needs: [create-release-tag, create-fix-tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "${{needs.create-release-tag.outputs.tag}}${{needs.create-fix-tag.outputs.tag}}" 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./${{ inputs.component_path }}
          file: ./${{ inputs.component_path }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            konstellation/${{ inputs.component_image }}:${{needs.create-release-tag.outputs.version}}${{needs.create-fix-tag.outputs.version}}
            konstellation/${{ inputs.component_image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
            rm -rf /tmp/.buildx-cache
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache
