# Dummy workflow to test the GitHub Actions
name: Dummy workflow

on:
  workflow_dispatch:


jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "Hello, world!"