name: Helm release workflow 

on:
  workflow_call:
    inputs:
      chart_file:
        required: true
        type: string
      chart_url:
        required: true
        type: string
      chart_path:
        required: true
        type: string
    secrets:
      pat:
        required: true

jobs:
  create-rc-tag:
    # Just after a workflow completes successfully and the workflows was triggered in main branch
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.rc_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.pat }}

      - name: Generate a pre-release
        id: rc_tag
        uses: intelygenz/monorepo-tagger-action@v1.2.2
        with:
          current-major: 0
          mode: 'product'
          type: 'pre-release'
          release-branch-prefix: "release/v"
          pre-release-name: 'rc'
          update-versions-in: '[{"file": "${{ inputs.chart_file }}", "property": "version"}]'
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}

  create-fix-tag:
    # Just after a workflow completes successfully and the workflows was triggered in a release branch
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'release')
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.fix_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.pat }}
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Generate a fix tag
        id: fix_tag
        uses: intelygenz/monorepo-tagger-action@v1.2.2
        with:
          mode: 'product'
          type: 'fix'
          release-branch-prefix: "release/v"
          update-versions-in: '[{"file": "${{ inputs.chart_file }}", "property": "version"}]'
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}

      - uses: azure/setup-helm@v1

      - uses: chrisdickinson/setup-yq@latest

      - name: Add repos
        run: |
          for i in $(yq r ct.yaml 'chart-repos'| sed -e 's/^- //')
          do
            NAME=$(echo $i | awk -F"=" '{print $1}')
            REPO=$(echo $i | awk -F"=" '{print $2}')
            helm repo add $NAME $REPO
          done

      - name: Chart releaser
        run: |
          # Download chart releaser
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.2.1/chart-releaser_1.2.1_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz
          rm -f cr.tar.gz
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
          exists=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/konstellation-io/$repo/releases/tags/$repo-${{ steps.fix_tag.outputs.tag }} -w %{http_code} -o /dev/null)
          if [[ $exists != "200" ]]; then
            echo "Creating release..."
            # package chart
            ./cr package ${{ inputs.chart_path }}/$repo
            # upload chart to github releases
            ./cr upload \
                --owner "$owner" \
                --git-repo "$repo" \
                --token "${{ secrets.GITHUB_TOKEN }}"
            # Update index and push to github pages
            ./cr index \
                --owner "$owner" \
                --git-repo "$repo" \
                --token "${{ secrets.GITHUB_TOKEN }}" \
                --charts-repo ${{ inputs.chart_url }} \
                --push
          else
            echo "Release already exists"
          fi
