name: Dockerfile linter

on:
  workflow_call:
    inputs:
      component_path:
        required: true
        type: string

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ./${{ inputs.component_path }}/Dockerfile
          format: tty
          config: ./.hadolint.yml
