name: New release workflow 

on:
  workflow_call:
    inputs:
      chart_file:
        required: true
        type: string
    secrets:
      pat:
        required: true

jobs:

  create-release-branch:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release_branch.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.pat }}

      - name: Generate a new release branch
        id: release_branch
        uses: intelygenz/monorepo-tagger-action@v1.2.2
        with:
          release-branch-prefix: "release/v"
          mode: 'product'
          type: 'new-release-branch'
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}

  create-release-tag:
    needs: create-release-branch
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.pat }}
          ref: ${{ needs.create-release-branch.outputs.tag }}

      - name: Generate a release
        id: release_tag
        uses: intelygenz/monorepo-tagger-action@v1.2.2
        with:
          mode: 'product'
          type: 'final'
          update-versions-in: '[{"file": "${{ inputs.chart_file }}", "property": "version"}]'
          tag-branch: ${{ needs.create-release-branch.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}

