name: New release
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - .github/workflows/new-release.yaml
      - .github/workflows/build.yaml
      - .github/workflows/helm-release.yaml
      - .github/workflows/chart-release.yaml

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PATNAME }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
        run: npx semantic-release
